// <auto-generated />
using System;
using Api.Modules.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Modules.AccessControl.Persistence.Migrations.Events
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20251202140732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Framework.SqlServer.Entities.Events.BusinessProcessEntity", b =>
                {
                    b.Property<string>("BusinessProcessId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkstreamId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusinessProcessId");

                    b.HasIndex("ProcessType", "InitiatedAt")
                        .HasDatabaseName("IX_BusinessProcesses_Type_Initiated");

                    b.HasIndex("WorkstreamId", "Status")
                        .HasDatabaseName("IX_BusinessProcesses_Workstream_Status");

                    b.ToTable("BusinessProcesses", "events");
                });

            modelBuilder.Entity("AccessControl.Framework.SqlServer.Entities.Events.StoredBusinessEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ActorIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AffectedEntities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessProcessId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("SessionCorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkstreamId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventId");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_BusinessEvents_Actor");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_BusinessEvents_Sequence");

                    b.HasIndex("BusinessProcessId", "SequenceNumber")
                        .HasDatabaseName("IX_BusinessEvents_Process_Sequence");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_BusinessEvents_Type_Occurred");

                    b.HasIndex("WorkstreamId", "EventCategory", "OccurredAt")
                        .HasDatabaseName("IX_BusinessEvents_Workstream_Category_Occurred");

                    b.ToTable("BusinessEvents", "events");
                });

            modelBuilder.Entity("AccessControl.Framework.SqlServer.Entities.Events.StoredBusinessEvent", b =>
                {
                    b.HasOne("AccessControl.Framework.SqlServer.Entities.Events.BusinessProcessEntity", "BusinessProcess")
                        .WithMany()
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
